---
- name: Add ppa Repository
  become: yes
  apt_repository: repo="{{ item }}"
  with_items: "{{ system_repos }}"
  when: ansible_os_family == 'Debian'

- name: Remove ppa Repository
  become: yes
  apt_repository: repo="{{ item }}" state=absent
  with_items: "{{ system_remove_repos }}"
  when: ansible_os_family == 'Debian'

- name: Update apt for today
  become: yes
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: If NTP doesn't exist, force apt update
  become: yes
  shell: "apt-cache show ntp || apt-get update"
  when: ansible_os_family == 'Debian'

- apt: name="{{ item }}" state=latest
  become: yes
  with_items: "{{ system_packages }}"
  when: ansible_os_family == 'Debian'

- yum: name="{{ item }}" state=latest
  become: yes
  with_items: "{{ system_packages }}"
  when: ansible_os_family == 'RedHat'
